---
# handlers file for ansible-maestro-java
- name: start maestro worker service
  when: maestro_worker_start_server is defined and maestro_worker_start_server == true
  become: true
  become_user: "{{ maestro_user }}"
  command: "{{ maestro_worker_install_dest }}/{{ maestro_worker_install_link }}/bin/maestro-worker-service start"
  listen: "start maestro worker service"

# Stop the instance
- name: stop maestro worker service
  when: maestro_worker_stop_server is defined and maestro_worker_stop_server == true
  become: true
  become_user: "{{ maestro_user }}"
  command: "{{ maestro_worker_install_dest }}/{{ maestro_worker_install_link }}/bin/maestro-worker-service stop"
  listen: "stop maestro worker service"

- name: restart maestro worker service
  when: maestro_worker_restart_server is defined and maestro_worker_restart_server == true
  become: true
  become_user: "{{ maestro_user }}"
  command: "{{ maestro_worker_install_dest }}/{{ maestro_worker_install_link }}/bin/maestro-worker-service restart"
  listen: "restart maestro worker service"

- name: restart maestro exporter service
  when: maestro_exporter_restart_server is defined and maestro_exporter_restart_server == true
  become: true
  become_user: "{{ maestro_user }}"
  command: "{{ maestro_exporter_install_dest }}/{{ maestro_exporter_install_link }}/bin/maestro-exporter-service restart"
  listen: "restart maestro exporter service"

- name: restart maestro inspector service
  when: maestro_inspector_restart_server is defined and maestro_inspector_restart_server == true
  become: true
  become_user: "{{ maestro_user }}"
  command: "{{ maestro_inspector_install_dest }}/{{ maestro_inspector_install_link }}/bin/maestro-inspector-service restart"
  listen: "restart maestro inspector service"

- name: restart maestro agent service
  when: maestro_agent_restart_server is defined and maestro_agent_restart_server == true
  become: true
  become_user: "{{ maestro_user }}"
  command: "{{ maestro_agent_install_dest }}/{{ maestro_agent_install_link }}/bin/maestro-agent-service restart"
  listen: "restart maestro agent service"


- name: restart maestro reports service
  when: maestro_reports_restart_server is defined and maestro_reports_restart_server == true
  become: true
  become_user: "{{ maestro_user }}"
  command: "{{ maestro_reports_install_dest }}/{{ maestro_reports_install_link }}/bin/maestro-reports-tool-service restart"
  listen: "restart maestro reports service"